### ISSUE TITLE
未ログイン・一般アカウントだと、拡張機能ボタンが表示されない問題

### ISSUE THREAD

**Issue by mujurin1** [Hemo2525/hemotool#1]
# 問題
未ログイン・一般アカウントの場合、再生の停止・再開ボタンが存在しません。
そのため、拡張機能ボタン が表示されず、また、常にコンソールログに
「[class^=___play-button___] が存在しません」
と表示され続けます。

また、予めログインした状態でコメビュ表示にして、ログアウトした場合、
コメントに名前は表示されますが、やはり拡張機能ボタンは表示されません。

# 想定していた挙動
未ログイン・一般の場合でも拡張機能ボタンが表示される。
あるいは、未ログイン・一般の場合は非対応と (ストアページ等で) 明記される。

**Comment by Hemo2525** [comment]
ソースの修正ありがとうございます！
頂いた修正をマージし、ストアに申請いたしました。
ストアの審査のため、数日で最新版(Ver 0.27)が公開されるかと思います。

**Comment by mujurin1** [comment]
ありがとうございます！
プルリクを送ったままのコードだとエラーがでてましたね…すみません
拡張機能の更新が待ち遠しいです
👍
